{{- if eq .Values.cloudprovider "openstack" }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: OpenstackConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-default
authUrl: {{ $nodepool.authUrl | quote }}
domainName: {{ $nodepool.domainName | quote }}
flavorName: {{ $nodepool.flavorName | quote }}
floatingipPool: {{ $nodepool.floatingipPool | quote }}
imageName: {{ $nodepool.imageName | quote }}
netName: {{ $nodepool.netName | quote }}
region: {{ $nodepool.region | quote }}
secGroups: {{ $nodepool.secGroups | quote }}
sshUser: {{ $nodepool.sshUser | quote }}
sshPort: {{ $nodepool.sshPort | quote }}
tenantName: {{ $nodepool.tenantName | quote }}
username: {{ $nodepool.username | quote }}
ipVersion: {{ $nodepool.ipVersion | quote }}
activeTimeout: {{ $nodepool.activeTimeout | quote }}
---
{{- end }}
{{- end }}
